### ISSUE TITLE
Crash on server

### ISSUE THREAD

**Issue by ElSaam** [WilliamEz/CustomDrones#14]
1.5.0 Crashing on server (forge-1.10.2-12.18.2.2099-universal)

**Comment by APolarBaer** [comment]
would probably help if you uploaded a log to pastebin >w<

**Comment by ElSaam** [comment]
nvrmnd works suddenly

**Comment by ElSaam** [comment]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Quark-r1.0-56.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.4.1.97-universal.jar)
  llibrary (llibrary-1.7.0-1.10.2.jar)
  lawnmower (lawnmower-1.0.1.jar)
  AdvancedRocketryPlugin (AdvancedRocketry-1.10.2-1.0.0RC2.jar)
  ItemPatchingLoader (ItemPhysic Full 1.3.4 mc1.10.2.jar)
  NWRTweak (redstonepaste-mc1.9.4-1.7.4.jar)
  BetterMinecraftChat (BetterMinecraftChat_1.10.2-4.1.6.jar)
  LoadingPlugin (Bloodmoon-MC1.9.4-1.4.1.jar)
  MalisisCorePlugin (malisiscore-1.10.2-4.2.7.jar)
  IC2core (industrialcraft-2-2.6.87-ex110.jar)
  Transformer (EnhancedChat-1.10.2-1.0.2.jar)
  IvToolkit (IvToolkit-1.2.8.5.jar)
  DepLoader (BrandonsCore-1.10.2-2.1.0.48-universal.jar)
  CreativePatchingLoader (CreativeCore v1.6.6 mc1.10.2.jar)
Contact their authors BEFORE contacting forge

// Would you like a cupcake?

Time: 11/13/16 10:01 PM
Description: Exception ticking world

java.lang.NullPointerException: Exception ticking world
    at williamle.drones.entity.EntityDroneBaby.initSpawnSetAppearance(EntityDroneBaby.java:69)
    at williamle.drones.entity.EntityDroneMob.initDroneInfo(EntityDroneMob.java:87)
    at williamle.drones.entity.EntityDroneBaby.initDroneInfo(EntityDroneBaby.java:64)
    at williamle.drones.entity.EntityDroneMob.onInitSpawn(EntityDroneMob.java:80)
    at williamle.drones.entity.EntityDroneMob.func_180482_a(EntityDroneMob.java:70)
    at net.minecraft.world.WorldEntitySpawner.func_77191_a(WorldEntitySpawner.java:275)
    at biomesoplenty.common.world.ChunkProviderGenerateBOP.func_185931_b(ChunkProviderGenerateBOP.java:542)
    at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1000)
    at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:983)
    at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:154)
    at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
    at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)
    at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:222)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
    at java.lang.Thread.run(Unknown Source)

## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Thread: Server thread
Stacktrace:
    at williamle.drones.entity.EntityDroneBaby.initSpawnSetAppearance(EntityDroneBaby.java:69)
    at williamle.drones.entity.EntityDroneMob.initDroneInfo(EntityDroneMob.java:87)
    at williamle.drones.entity.EntityDroneBaby.initDroneInfo(EntityDroneBaby.java:64)
    at williamle.drones.entity.EntityDroneMob.onInitSpawn(EntityDroneMob.java:80)
    at williamle.drones.entity.EntityDroneMob.func_180482_a(EntityDroneMob.java:70)
    at net.minecraft.world.WorldEntitySpawner.func_77191_a(WorldEntitySpawner.java:275)
    at biomesoplenty.common.world.ChunkProviderGenerateBOP.func_185931_b(ChunkProviderGenerateBOP.java:542)
    at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1000)
    at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:983)
    at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:154)
    at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
    at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)
    at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:222)

-- Affected level --
Details:
    Level name: world
    All players: 1 total; [EntityPlayerMP['El_Saam'/686, l='world', x=285.48, y=62.15, z=342.23]]
    Chunk stats: ServerChunkCache: 1073 Drop: 0
    Level seed: -6457429814587550420
    Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: true
    Level generator options: 
    Level spawn location: World: (156,64,252), Chunk: (at 12,4,12 in 9,15; contains blocks 144,0,240 to 159,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 48631 game time, 0 day time
    Level dimension: 0
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 109784 (now: false), thunder time: 94979 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
    at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
    Minecraft Version: 1.10.2
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_111, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 3123663224 bytes (2978 MB) / 4002938880 bytes (3817 MB) up to 4002938880 bytes (3817 MB)
    JVM Flags: 2 total; -Xms4G -Xmx4G
    IntCache: cache: 1, tcache: 1, allocated: 3, tallocated: 104
    FML: MCP 9.32 Powered by Forge 12.18.2.2099 80 mods loaded, 80 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader](forge-1.10.2-12.18.2.2099-universal.jar) 
    UCHIJAAAA   Forge{12.18.2.2099} [Minecraft Forge](forge-1.10.2-12.18.2.2099-universal.jar) 
    UCHIJAAAA   AdvancedRocketry{1} [Advanced Rocketry](minecraft.jar) 
    UCHIJAAAA   creativecoredummy{1.0.0} [CreativeCoreDummy](minecraft.jar) 
    UCHIJAAAA   itemphysic{1.3.0} [ItemPhysic](minecraft.jar) 
    UCHIJAAAA   ivtoolkit{1.2.8.5} [IvToolkit](minecraft.jar) 
    UCHIJAAAA   libVulpes{0.1.7.20161108155707} [libVulpes](LibVulpes-1.10.2-0.1.7-universal.jar) 
    UCHIJAAAA   advancedRocketry{1.10.2-1.0.0RC2} [Advanced Rocketry](AdvancedRocketry-1.10.2-1.0.0RC2.jar) 
    UCHIJAAAA   architecturecraft{1.7.0} [ArchitectureCraft](ArchitectureCraft-1.7.0-mc1.10.2.jar) 
    UCHIJAAAA   Quark{r1.0-56} [Quark](Quark-r1.0-56.jar) 
    UCHIJAAAA   AutoRegLib{1.0-2} [AutoRegLib](AutoRegLib-1.0-2.jar) 
    UCHIJAAAA   babymobs{1.5.1} [Baby Mobs](BabyMobs-1.10.2-1.5.1.jar) 
    UCHIJAAAA   basemetals{2.4.0} [Base Metals](BaseMetals_1.10.2-2.4.0.11.jar) 
    UCHIJAAAA   BiomesOPlenty{5.0.0.2089} [Biomes O' Plenty](BiomesOPlenty-1.10.2-5.0.0.2089-universal.jar) 
    UCHIJAAAA   Bloodmoon{1.2} [Bloodmoon](Bloodmoon-MC1.9.4-1.4.1.jar) 
    UCHIJAAAA   brandonscore{2.1.0} [Brandon's Core](BrandonsCore-1.10.2-2.1.0.48-universal.jar) 
    UCHIJAAAA   cavern{1.1.1} [Cavern](Cavern_1.10-v1.1.1.jar) 
    UCHIJAAAA   chiselsandbits{12.5} [Chisels & Bits](chiselsandbits-12.5.jar) 
    UCHIJAAAA   cookingforblockheads{4.2.16} [Cooking for Blockheads](CookingForBlockheads_1.10.2-4.2.16.jar) 
    UCHIJAAAA   coroai{v1.1.9} [coroai](coroutil-1.10.2-1.1.9.jar) 
    UCHIJAAAA   extendedrenderer{v1.0} [Extended Renderer](coroutil-1.10.2-1.1.9.jar) 
    UCHIJAAAA   configmod{v1.0} [Extended Mod Config](coroutil-1.10.2-1.1.9.jar) 
    UCHIJAAAA   creativecore{1.5.0} [CreativeCore](CreativeCore v1.6.6 mc1.10.2.jar) 
    UCHIJAAAA   drones{1.10.2-1.5.0} [CustomDrones](CustomDrones-1.5.0-mc1.10.2.jar) 
    UCHIJAAAA   cyberware{beta-0.2.4} [Cyberware](cyberware-1.9.4-1.10.2-beta-0.2.4.jar) 
    UCHIJAAAA   DrugsGalore{1.6} [DrugsGalore](dg160.jar) 
    UCHIJAAAA   draconicevolution{2.0.0d} [Draconic Evolution](Draconic-Evolution-1.10.2-2.0.0d.107-universal.jar) 
    UCHIJAAAA   lootablebodies{2.2.0} [DrCyano's Lootable Bodies](DrCyanosLootableBodies_1.10.2-2.2.0.jar) 
    UCHIJAAAA   ea{v2.4.7a-mc1.10.2} [Ebon Arts](EbonArts-v2.4.7a-mc1.10.2.jar) 
    UCHIJAAAA   poweradvantage{2.3.0} [Power Advantage](PowerAdvantage_1.10.2-2.3.0.jar) 
    UCHIJAAAA   electricadvantage{2.2.0} [Electric Advantage](ElectricAdvantage_1.10.2-2.2.0.jar) 
    UCHIJAAAA   enhancedchat{1.0.2} [EnhancedChat](EnhancedChat-1.10.2-1.0.2.jar) 
    UCHIJAAAA   extraalchemy{0.3.0.2-release} [Extra Alchemy](extraalchemy-0.3.0.2-release.jar) 
    UCHIJAAAA   glasscraftmod{1.0} [Glasscraft](Glasscraftmod v1.0 - MC1.10.2 Forge.jar) 
    UCHIJAAAA   grapple_hooks{1.0.8} [Grapple Hooks](Grapple-Hooks-1.10.2-1.0.8.jar) 
    UCHIJAAAA   howlingmoon{0.5Core} [Howling Moon Rising](howlingmoon-1.10.2-0.5Core.jar) 
    UCHIJAAAA   mantle{1.10.2-1.0.0.jenkins170} [Mantle](Mantle-1.10.2-1.0.0.jar) 
    UCHIJAAAA   tconstruct{1.10.2-2.5.6b.jenkins424} [Tinkers' Construct](TConstruct-1.10.2-2.5.6b.jar) 
    UCHIJAAAA   immersiveengineering{0.10-44} [Immersive Engineering](ImmersiveEngineering-0.10-44.jar) 
    UCHIJAAAA   IC2{2.6.87-ex110} [IndustrialCraft 2](industrialcraft-2-2.6.87-ex110.jar) 
    UCHIJAAAA   InventoryPets{1.4.8.2} [Inventory Pets](inventorypets-1.10-1.4.8.2.jar) 
    UCHIJAAAA   llibrary{1.7.0} [LLibrary](llibrary-1.7.0-1.10.2.jar) 
    UCHIJAAAA   jurassicraft{2.0.4} [JurassiCraft](JurassiCraft-2.0.4.jar) 
    UCHIJAAAA   lawnmower{1.0.1} [Lawnmower](lawnmower-1.0.1.jar) 
    UCHIJAAAA   malisiscore{1.10.2-4.2.7} [MalisisCore](malisiscore-1.10.2-4.2.7.jar) 
    UCHIJAAAA   malisisdoors{1.10.2-5.1.4} [MalisisDoors](malisisdoors-1.10.2-5.1.4.jar) 
    UCHIJAAAA   RadixCore{1.10.2-2.1.3} [RadixCore](RadixCore-1.10.2-2.1.3-universal.jar) 
    UCHIJAAAA   MCA{1.10.2-5.2.3} [Minecraft Comes Alive](MCA-1.10.2-5.2.3-universal.jar) 
    UCHIJAAAA   mfs{7.0.1} [Minecraft Flight Simulator](Minecraft Flight Simulator-1.10.2-7.0.1.jar) 
    UCHIJAAAA   missing_pieces{4.0.2} [Missing Pieces](missing_pieces-1.10.2-4.0.2.jar) 
    UCHIJAAAA   reborncore{2.7.3.46} [RebornCore](RebornCore-1.10.2-2.7.3.46-universal.jar) 
    UCHIJAAAA   techreborn{1.4.7.70} [TechReborn](TechReborn-1.10.2-1.4.7.70-universal.jar) 
    UCHIJAAAA   moarsigns{4.0.1.4} [MoarSigns](MoarSigns-1.10.2-4.0.1.4.jar) 
    UCHIJAAAA   mobends{0.22.5} [Mo'Bends](mobends-0.22.5_for_MC-1.10.2.jar) 
    UCHIJAAAA   orespawn{1.1.0} [Ore Spawn](OreSpawn_1.10.2-1.1.0.jar) 
    UCHIJAAAA   harvestcraft{1.9.4-1.10.2f} [Pam's HarvestCraft](Pam's HarvestCraft 1.9.4-1.10.2f.jar) 
    UCHIJAAAA   pandorasbox{2.1.5} [Pandora's Box](PandorasBox-2.1.5.jar) 
    UCHIJAAAA   parachutemod{1.5.2} [Parachute Mod](parachutemod-ng-1.10.2-1.5.2-409.jar) 
    UCHIJAAAA   placemod{3.8} [Placemod](placemod-3.8-1.10.2.jar) 
    UCHIJAAAA   ppapmod{1.4.0} [PPAP Mod](PPAP Mod-1.10.2-1.4.0.jar) 
    UCHIJAAAA   reap{1.3.1} [Reap Mod](ReapMod 1.3.1.jar) 
    UCHIJAAAA   reborncore-mcmultipart{2.7.3.46} [reborncore-MCMultiPart](RebornCore-1.10.2-2.7.3.46-universal.jar) 
    UCHIJAAAA   redstonepaste{1.7.4} [Redstone Paste](redstonepaste-mc1.9.4-1.7.4.jar) 
    UCHIJAAAA   xreliquary{1.10.2-1.3.3.571} [Reliquary](Reliquary-1.10.2-1.3.3.571.jar) 
    UCHIJAAAA   rftools{5.53} [RFTools](rftools-1.10-5.53.jar) 
    UCHIJAAAA   Roguelike{1.5.4} [Roguelike Dungeons](RoguelikeDungeons-1.10.2-1.5.4.jar) 
    UCHIJAAAA   shadowmc{3.4.9} [ShadowMC](ShadowMC-1.10.2-3.4.9.jar) 
    UCHIJAAAA   signpic{2.1.5} [SignPicture](SignPicture-1.10.2-2.1.5-universal.jar) 
    UCHIJAAAA   flammpfeil.slashblade{mc1.10.2-r23} [SlashBlade](SlashBlade-mc1.10.2-r23.jar) 
    UCHIJAAAA   SleepingBag{1.3.0} [Sleeping Bag](SleepingBag-1.10.2-1.3.0.jar) 
    UCHIJAAAA   thutessentials{1.3.1} [Thut Essentials](thutessentials-1.5.3.jar) 
    UCHIJAAAA   totemic{1.9.4-0.7.8.1} [Totemic](Totemic-1.9.4-0.7.8.1.jar) 
    UCHIJAAAA   vampirism{1.0.1} [Vampirism](Vampirism-1.10.2-1.0.1.jar) 
    UCHIJAAAA   teamlapen-lib{1.0.1} [TeamLapen Library](Vampirism-1.10.2-1.0.1.jar) 
    UCHIJAAAA   vc{v2.7.2a-mc1.10.2} [ViesCraft](ViesCraft-2.7.2a-mc1.10.2.jar) 
    UCHIJAAAA   weather2{v2.3.15} [Localized Weather & Storms](weather2-1.10.2-2.3.15.jar) 
    UCHIJAAAA   wired{1.3.3} [WIRED: More Augs](WIRED-1.3.3.jar) 
    UCHIJAAAA   worldedit{6.1.4} [WorldEdit](worldedit-forge-mc1.10.2-6.1.4-dist.jar) 
    UCHIJAAAA   zombieawareness{v1.20} [Zombie Awareness](zombieawareness-1.10.2-1.20.jar) 
    Loaded coremods (and transformers): 
LoadingPlugin (Quark-r1.0-56.jar)
  vazkii.quark.base.asm.ClassTransformer
CCLCorePlugin (CodeChickenLib-1.10.2-2.4.1.97-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
llibrary (llibrary-1.7.0-1.10.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
lawnmower (lawnmower-1.0.1.jar)
  net.ilexiconn.lawnmower.server.asm.patcher.LawnmowerRuntimePatcher
AdvancedRocketryPlugin (AdvancedRocketry-1.10.2-1.0.0RC2.jar)
  zmaster587.advancedRocketry.asm.ClassTransformer
ItemPatchingLoader (ItemPhysic Full 1.3.4 mc1.10.2.jar)
  com.creativemd.itemphysic.ItemTransformer
NWRTweak (redstonepaste-mc1.9.4-1.7.4.jar)
  net.fybertech.nwr.NWRTransformer
BetterMinecraftChat (BetterMinecraftChat_1.10.2-4.1.6.jar)
  net.blay09.mods.bmc.coremod.ClassTransformer
LoadingPlugin (Bloodmoon-MC1.9.4-1.4.1.jar)
  lumien.bloodmoon.asm.ClassTransformer
MalisisCorePlugin (malisiscore-1.10.2-4.2.7.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
  net.malisis.core.util.clientnotif.ClientNotifTransformer
IC2core (industrialcraft-2-2.6.87-ex110.jar)

Transformer (EnhancedChat-1.10.2-1.0.2.jar)
  coolsquid.enhancedchat.asm.Transformer
IvToolkit (IvToolkit-1.2.8.5.jar)

DepLoader (BrandonsCore-1.10.2-2.1.0.48-universal.jar)

CreativePatchingLoader (CreativeCore v1.6.6 mc1.10.2.jar)

```
Pulsar/tconstruct loaded Pulses: 
    - TinkerCommons (Enabled/Forced)
    - TinkerWorld (Enabled/Not Forced)
    - TinkerTools (Enabled/Not Forced)
    - TinkerHarvestTools (Enabled/Forced)
    - TinkerMeleeWeapons (Enabled/Forced)
    - TinkerRangedWeapons (Enabled/Forced)
    - TinkerModifiers (Enabled/Forced)
    - TinkerSmeltery (Enabled/Not Forced)
    - TinkerGadgets (Enabled/Not Forced)
    - TinkerOredict (Enabled/Forced)
    - TinkerIntegration (Enabled/Forced)
    - TinkerFluids (Enabled/Forced)
    - TinkerMaterials (Enabled/Forced)
    - TinkerModelRegister (Enabled/Forced)
    - chiselsandbitsIntegration (Enabled/Not Forced)

Profiler Position: N/A (disabled)
Player Count: 1 / 20; [EntityPlayerMP['El_Saam'/686, l='world', x=285.48, y=62.15, z=342.23]]
Is Modded: Definitely; Server brand changed to 'fml,forge'
Type: Dedicated Server (map_server.txt)
```

**Comment by APolarBaer** [comment]
its the same as #15 and #11
