### ISSUE TITLE
Error on Dedicated Server

### ISSUE THREAD

**Issue by psychofad** [WilliamEz/CustomDrones#2]
I keep getting an error in the console of my server when trying to interact with the drone.  This particular error was from simply connecting it to a controller.  In addition to that I cannot right click a mod into a drone, and when I try to do it from the inventory of the drone it's like all the inventory spaces are shifted somehow a few spaces over, so when I think I will be picking up a mod, I actually pick up another item in my inventory that is quite a few spaces from the mod.

`[17:16:53] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: net.minecraft.entity.player.EntityPlayer.func_174824_e(F)Lnet/minecraft/util/math/Vec3d;
        at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_91]
        at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_91]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
Caused by: java.lang.NoSuchMethodError: net.minecraft.entity.player.EntityPlayer.func_174824_e(F)Lnet/minecraft/util/math/Vec3d;
        at williamle.drones.item.ItemDroneFlyer.func_77659_a(ItemDroneFlyer.java:34) ~[ItemDroneFlyer.class:?]
        at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:162) ~[adz.class:?]
        at net.minecraft.server.management.PlayerInteractionManager.func_187250_a(PlayerInteractionManager.java:365) ~[lv.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:710) ~[me.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:32) ~[jk.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:9) ~[jk.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_91]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_91]
        at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
        ... 5 more`

If I do manage to get the actual mod, once I put it into the slot and click the install upgrade button, I get crashed to desktop with the following crash report.

[http://pastebin.com/fTs5PiUS](url)

**Comment by psychofad** [comment]
I should mention this is in my server modpack

[http://www.technicpack.net/modpack/psychosis-decupled.870859](url)

The Overview has a list of the mods included in the pack

**Comment by WilliamEz** [comment]
That is because I chose to use a client method instead of a server method, my bad :P

**Comment by WilliamEz** [comment]
Would you mind checking for me if all those problems you mentioned still persist?
Thanks :D

**Comment by psychofad** [comment]
I tested the new version and it appears you have fixed all the weirdness and crashes I was experiencing!

There are a couple of other things I noticed.

Whenever the GUI overlaps JEI (and I have Forever Enough Items so I'm not sure if its because of that) If I click on a space in the Inventory that has an item behind it in JEI it will open the recipe/give the item/let you delete an item you are holding depending on what mode (cheat/recipe) you are in.  If there is some way you could block that interaction while you GUI is open that would be great.

The other thing was even though everything was working without issue, I was still getting this error in the server console and I am not sure what I was doing when it happened:

`[18:17:27] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: com/mojang/realmsclient/gui/ChatFormatting
        at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_91]
        at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_91]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
Caused by: java.lang.NoClassDefFoundError: com/mojang/realmsclient/gui/ChatFormatting
        at williamle.drones.item.ItemDroneFlyer.interactWithDrone(ItemDroneFlyer.java:82) ~[ItemDroneFlyer.class:?]
        at williamle.drones.drone.EntityDrone.func_184199_a(EntityDrone.java:235) ~[EntityDrone.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPlayServer.java:1029) ~[me.class:?]
        at net.minecraft.network.play.client.CPacketUseEntity.func_148833_a(SourceFile:68) ~[iu.class:?]
        at net.minecraft.network.play.client.CPacketUseEntity.func_148833_a(SourceFile:12) ~[iu.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_91]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_91]
        at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]`

I will say tho, flying that thing manually takes a bit of practice for sure, not sure if the WASD controls can be fine tuned at all, but if it were me I would make it so that W=away from controller (level movement), A=just like it is, S=Towards the controller (level movement), D=just like it is, SPACE=Up, SHIFT=Down.  As it is it appears to take into account the angle you are looking at which adds to the confusion for flying it in my opinion.  Once you have picked yourself up the controls seem to be as I described for flying yourself around.

Anyways, just my 2 cents.  Thanks for making this awesome mod!  I look forward to seeing it develop further!

**Comment by WilliamEz** [comment]
Thank you for your comments :D I really appreciate them.
WASD control may get revamped later, but for now they do take your look angle into account.
I'll fix that crash in the next update and I'll see if I can work with the JEI.

**Comment by WilliamEz** [comment]
Should be fixed in 1.5.0
